### ISSUE TITLE
Regex search in make_gtf_sane returns None

### ISSUE THREAD

**Issue by cademirch** [Gaius-Augustus/MakeHub#11]
I'm trying to make an assembly hub for [this assembly](https://www.ncbi.nlm.nih.gov/assembly/GCF_000008025.1), using this command: 
```
python3 MakeHub/make_hub.py -e cmirchan@ucsc.edu -g GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_genomic.fna -L "Wolbachia endosymbiont of Drosophila melanogaster (a-proteobacteria)" -l "Wmel" -V GCF_000008025.1_ASM802v1 -a GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_genomic.gtf
```

However, I get this error:
```
Traceback (most recent call last):
  File "MakeHub/make_hub.py", line 1862, in <module>
    make_gtf_sane(args.annot, ucsc_file)
  File "MakeHub/make_hub.py", line 586, in make_gtf_sane
    r'(\S+)(\t\S+\t\S+\t\d+\t\d+\t\S+\t)(\S+)(\t\S+\t).*transcript_id\s\"(\S+)\"', line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

So it seems like the regex search at line 586 is returning None. Would appreciate any help with this.

**Comment by KatharinaHoff** [comment]
I fixed this. Thank you for providing data details that made it very easy to inspect this issue.

https://github.com/Gaius-Augustus/MakeHub/commit/8f4a1831a1e1518cefb49c03f6c128deb3dd0b77

I also made a release today.

**Comment by cademirch** [comment]
> I fixed this. Thank you for providing data details that made it very easy to inspect this issue.
> 
> 
> 
> https://github.com/Gaius-Augustus/MakeHub/commit/8f4a1831a1e1518cefb49c03f6c128deb3dd0b77
> 
> 
> 
> I also made a release today.

Awesome, thanks!
