### ISSUE TITLE
Error in file make_hub.py at line 524

### ISSUE THREAD

**Issue by mapsm** [Gaius-Augustus/MakeHub#6]
Hello!

I'm trying to create a new assembly hub using example 1, this is the command:

make_hub.py -l wflax -L "looong" -g /annotation/final_assembly.fa -n -e \ email@gmail.com

The program terminates with this: 

Generating genome 2bit file ./wflax/wflax/wflax.2bit...
Generating chromsome size info file ./wflax/wflax/wflax.chrom.sizes...
Generating variable step wiggle file for GC content ./tmp-wflax/wflax.gc5Base.wigVarStep.gz...
Generating bigWig file for GC content ./wflax/wflax/wflax.gc5Base.bw...
Error in file /miniconda2/envs/py365/bin/make_hub.py at line 524: Return code of subprocess was 255['/miniconda2/envs/py365/bin/wigToBigWig', './tmp-wflax/wflax.gc5Base.wigVarStep.gz', './wflax/wflax/wflax.chrom.sizes', './wflax/wflax/wflax.gc5Base.bw']

Any insight would be appreciated. Thank you.

**Comment by KatharinaHoff** [comment]
I tried to reproduce the problem by installing MakeHub from conda. I don't have miniconda, though. However, the conda install just failed completely for me. Therefore I cannot locally reproduce the problem. (I am not maintainer of the conda package.)

Can you please try to manually execute

/miniconda2/envs/py365/bin/wigToBigWig ./tmp-wflax/wflax.gc5Base.wigVarStep.gz ./wflax/wflax/wflax.chrom.sizes ./wflax/wflax/wflax.gc5Base.bw

and see what kind of error message is returned?

Katharina

**Comment by mapsm** [comment]
Hi Katharina, 

The message returned is:

$ chromosome` ScgDGns_1;HRSCAF is not in chrom sizes file

However, this chromosome is in the file  [wflax.chrom.sizes.txt](https://github.com/Gaius-Augustus/MakeHub/files/4323391/wflax.chrom.sizes.txt)

Maybe the problem is related with the long name or something else in the file format.
 What do you think I should do to fix it? 

Thanks for your help and quick response 

Pilar

**Comment by KatharinaHoff** [comment]
I am not sure but I assume that special characters in sequence names, such as ; or | are treated as separation characters by some tools. In this case, it's a UCSC tool that has a problem with the sequence name. I cannot fix that. Therefore, I recommend to simplify fasta headers.

**Comment by mapsm** [comment]
It worked! I changed the headers using fyFastaHeaders.pl
Thank you
