### ISSUE TITLE
MakeHub fails while creating cytoBand track

### ISSUE THREAD

**Issue by fhorvat** [Gaius-Augustus/MakeHub#7]
Hello, thank you for the very useful tool. I'm having a problem in creating a hub after I changed scaffold names in the assembly. 

This is a command I'm running:
```
/common/bin/MakeHub/make_hub.py \
--email xxx@xxx.com \
--genome ./HiC_assembly.fasta \
--long_label "HiC assembly" \
--short_label HiC_assembly \
--assembly_version 1 \
--latin_name "HiC assembly" \
--gene_track ./HiC_assembly.gtf HiC_assembly_annotation
```

Assembly has following scaffold names:

> HiC_scaffold_16
> HiC_scaffold_14
> HiC_scaffold_17
> HiC_scaffold_5
> HiC_scaffold_9
> HiC_scaffold_22
> HiC_scaffold_13
> HiC_scaffold_10
> HiC_scaffold_1
> HiC_scaffold_8
> HiC_scaffold_3
> HiC_scaffold_4
> HiC_scaffold_12
> HiC_scaffold_18
> HiC_scaffold_20
> HiC_scaffold_6
> HiC_scaffold_15
> HiC_scaffold_11
> HiC_scaffold_21
> HiC_scaffold_19
> HiC_scaffold_2
> HiC_scaffold_7

This is a log file with the error:

> Generating genome 2bit file ./HiC_assembly/HiC_assembly/HiC_assembly.2bit...
> Generating chromsome size info file ./HiC_assembly/HiC_assembly/HiC_assembly.chrom.sizes...
> Generating variable step wiggle file for GC content ./tmp-HiC_assembly/HiC_assembly.gc5Base.wigVarStep.gz...
> Generating bigWig file for GC content ./HiC_assembly/HiC_assembly/HiC_assembly.gc5Base.bw...
> Generating cytoband track...
> Generating bigBed file for ./tmp-HiC_assembly/HiC_assembly.cytoband.bed...
> Error in file /common/bin/MakeHub/make_hub.py at line 524: Return code of subprocess was 255['/common/bin/UCSC/bedToBigBed', '-type=bed4', './tmp-HiC_assembly/HiC_assembly.cytoband.bed', '-as=/common/bin/MakeHub/cytoBand.as', './HiC_assembly/HiC_assembly/HiC_assembly.chrom.sizes', './HiC_assembly/HiC_assembly/cytoBandIdeo.bb']
> 

When I paste this command and try to run it directly from the command line:
```
/common/bin/UCSC/bedToBigBed -type=bed4 ./tmp-HiC_assembly/HiC_assembly.cytoband.bed -as=/common/bin/MakeHub/cytoBand.as ./HiC_assembly/HiC_assembly/HiC_assembly.chrom.sizes ./HiC_assembly/HiC_assembly/cytoBandIdeo.bb
```

this is the error I get:

> ./tmp-HiC_assembly/HiC_assembly.cytoband.bed is not case-sensitive sorted at line 2.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

If I try to sort file ./tmp-HiC_assembly/HiC_assembly.cytoband.bed using command:
```
LC_COLLATE=C sort -k1,1 -k2,2n ./tmp-HiC_assembly/HiC_assembly.cytoband.bed > HiC_assembly.cytoband.sorted.bed
```

then the above command with sorted .bed file instead of original .bed works. So the problem seems to in sorting scaffold names. Is there a way to fix this problem? Thank you in advance for your help.

**Comment by KatharinaHoff** [comment]
This issue was solved in commit https://github.com/Gaius-Augustus/MakeHub/commit/b5175ed36dfbd020ed0ac06c3907b14347d60504
