### ISSUE TITLE
Bio.Alphabet issue

### ISSUE THREAD

**Issue by Sher-Ojala** [Gaius-Augustus/MakeHub#8]
Hello!

I am having some issues with installing the MakeHub due to Bio.Alphabet.  I do have biophython installed.  Can you help me?

Traceback (most recent call last):
  File "make_hub.py", line 24, in <module>
    from Bio.Alphabet import generic_dna, generic_protein
  File "/root/anaconda3/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_hub.py", line 32, in <module>
    'Try installing with \"pip3 install biopython\"')
ImportError: In file make_hub.py at line 28: Failed to import biophython modules. Try installing with "pip3 install biopython"

Thank you in advance for any help!
Sher

**Comment by KatharinaHoff** [comment]
Hi Sher,
I hope this commit: https://github.com/Gaius-Augustus/MakeHub/commit/d0a802532dcc98ee3d75dccd8d80b321f69a278c 
fixed your problem.
Best,
Katharina

**Comment by Sher-Ojala** [comment]
Thank you!
Sher
